# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/miman/Desktop/MIMAN_GS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/miman/Desktop/MIMAN_GS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miman/Desktop/MIMAN_GS/CMakeFiles /home/miman/Desktop/MIMAN_GS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miman/Desktop/MIMAN_GS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MIMAN

# Build rule for target.
MIMAN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MIMAN
.PHONY : MIMAN

# fast build rule for target.
MIMAN/fast:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/build
.PHONY : MIMAN/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/miman_autopilot.o: src/miman_autopilot.cpp.o

.PHONY : src/miman_autopilot.o

# target to build an object file
src/miman_autopilot.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_autopilot.cpp.o
.PHONY : src/miman_autopilot.cpp.o

src/miman_autopilot.i: src/miman_autopilot.cpp.i

.PHONY : src/miman_autopilot.i

# target to preprocess a source file
src/miman_autopilot.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_autopilot.cpp.i
.PHONY : src/miman_autopilot.cpp.i

src/miman_autopilot.s: src/miman_autopilot.cpp.s

.PHONY : src/miman_autopilot.s

# target to generate assembly for a file
src/miman_autopilot.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_autopilot.cpp.s
.PHONY : src/miman_autopilot.cpp.s

src/miman_coms.o: src/miman_coms.cpp.o

.PHONY : src/miman_coms.o

# target to build an object file
src/miman_coms.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_coms.cpp.o
.PHONY : src/miman_coms.cpp.o

src/miman_coms.i: src/miman_coms.cpp.i

.PHONY : src/miman_coms.i

# target to preprocess a source file
src/miman_coms.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_coms.cpp.i
.PHONY : src/miman_coms.cpp.i

src/miman_coms.s: src/miman_coms.cpp.s

.PHONY : src/miman_coms.s

# target to generate assembly for a file
src/miman_coms.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_coms.cpp.s
.PHONY : src/miman_coms.cpp.s

src/miman_config.o: src/miman_config.cpp.o

.PHONY : src/miman_config.o

# target to build an object file
src/miman_config.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_config.cpp.o
.PHONY : src/miman_config.cpp.o

src/miman_config.i: src/miman_config.cpp.i

.PHONY : src/miman_config.i

# target to preprocess a source file
src/miman_config.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_config.cpp.i
.PHONY : src/miman_config.cpp.i

src/miman_config.s: src/miman_config.cpp.s

.PHONY : src/miman_config.s

# target to generate assembly for a file
src/miman_config.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_config.cpp.s
.PHONY : src/miman_config.cpp.s

src/miman_csp.o: src/miman_csp.cpp.o

.PHONY : src/miman_csp.o

# target to build an object file
src/miman_csp.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_csp.cpp.o
.PHONY : src/miman_csp.cpp.o

src/miman_csp.i: src/miman_csp.cpp.i

.PHONY : src/miman_csp.i

# target to preprocess a source file
src/miman_csp.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_csp.cpp.i
.PHONY : src/miman_csp.cpp.i

src/miman_csp.s: src/miman_csp.cpp.s

.PHONY : src/miman_csp.s

# target to generate assembly for a file
src/miman_csp.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_csp.cpp.s
.PHONY : src/miman_csp.cpp.s

src/miman_ftpfcd.o: src/miman_ftpfcd.cpp.o

.PHONY : src/miman_ftpfcd.o

# target to build an object file
src/miman_ftpfcd.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_ftpfcd.cpp.o
.PHONY : src/miman_ftpfcd.cpp.o

src/miman_ftpfcd.i: src/miman_ftpfcd.cpp.i

.PHONY : src/miman_ftpfcd.i

# target to preprocess a source file
src/miman_ftpfcd.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_ftpfcd.cpp.i
.PHONY : src/miman_ftpfcd.cpp.i

src/miman_ftpfcd.s: src/miman_ftpfcd.cpp.s

.PHONY : src/miman_ftpfcd.s

# target to generate assembly for a file
src/miman_ftpfcd.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_ftpfcd.cpp.s
.PHONY : src/miman_ftpfcd.cpp.s

src/miman_ftprdp.o: src/miman_ftprdp.cpp.o

.PHONY : src/miman_ftprdp.o

# target to build an object file
src/miman_ftprdp.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_ftprdp.cpp.o
.PHONY : src/miman_ftprdp.cpp.o

src/miman_ftprdp.i: src/miman_ftprdp.cpp.i

.PHONY : src/miman_ftprdp.i

# target to preprocess a source file
src/miman_ftprdp.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_ftprdp.cpp.i
.PHONY : src/miman_ftprdp.cpp.i

src/miman_ftprdp.s: src/miman_ftprdp.cpp.s

.PHONY : src/miman_ftprdp.s

# target to generate assembly for a file
src/miman_ftprdp.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_ftprdp.cpp.s
.PHONY : src/miman_ftprdp.cpp.s

src/miman_imgui.o: src/miman_imgui.cpp.o

.PHONY : src/miman_imgui.o

# target to build an object file
src/miman_imgui.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_imgui.cpp.o
.PHONY : src/miman_imgui.cpp.o

src/miman_imgui.i: src/miman_imgui.cpp.i

.PHONY : src/miman_imgui.i

# target to preprocess a source file
src/miman_imgui.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_imgui.cpp.i
.PHONY : src/miman_imgui.cpp.i

src/miman_imgui.s: src/miman_imgui.cpp.s

.PHONY : src/miman_imgui.s

# target to generate assembly for a file
src/miman_imgui.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_imgui.cpp.s
.PHONY : src/miman_imgui.cpp.s

src/miman_model.o: src/miman_model.cpp.o

.PHONY : src/miman_model.o

# target to build an object file
src/miman_model.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_model.cpp.o
.PHONY : src/miman_model.cpp.o

src/miman_model.i: src/miman_model.cpp.i

.PHONY : src/miman_model.i

# target to preprocess a source file
src/miman_model.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_model.cpp.i
.PHONY : src/miman_model.cpp.i

src/miman_model.s: src/miman_model.cpp.s

.PHONY : src/miman_model.s

# target to generate assembly for a file
src/miman_model.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_model.cpp.s
.PHONY : src/miman_model.cpp.s

src/miman_orbital.o: src/miman_orbital.cpp.o

.PHONY : src/miman_orbital.o

# target to build an object file
src/miman_orbital.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_orbital.cpp.o
.PHONY : src/miman_orbital.cpp.o

src/miman_orbital.i: src/miman_orbital.cpp.i

.PHONY : src/miman_orbital.i

# target to preprocess a source file
src/miman_orbital.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_orbital.cpp.i
.PHONY : src/miman_orbital.cpp.i

src/miman_orbital.s: src/miman_orbital.cpp.s

.PHONY : src/miman_orbital.s

# target to generate assembly for a file
src/miman_orbital.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_orbital.cpp.s
.PHONY : src/miman_orbital.cpp.s

src/miman_radial.o: src/miman_radial.cpp.o

.PHONY : src/miman_radial.o

# target to build an object file
src/miman_radial.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_radial.cpp.o
.PHONY : src/miman_radial.cpp.o

src/miman_radial.i: src/miman_radial.cpp.i

.PHONY : src/miman_radial.i

# target to preprocess a source file
src/miman_radial.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_radial.cpp.i
.PHONY : src/miman_radial.cpp.i

src/miman_radial.s: src/miman_radial.cpp.s

.PHONY : src/miman_radial.s

# target to generate assembly for a file
src/miman_radial.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_radial.cpp.s
.PHONY : src/miman_radial.cpp.s

src/miman_s_control.o: src/miman_s_control.cpp.o

.PHONY : src/miman_s_control.o

# target to build an object file
src/miman_s_control.cpp.o:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_s_control.cpp.o
.PHONY : src/miman_s_control.cpp.o

src/miman_s_control.i: src/miman_s_control.cpp.i

.PHONY : src/miman_s_control.i

# target to preprocess a source file
src/miman_s_control.cpp.i:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_s_control.cpp.i
.PHONY : src/miman_s_control.cpp.i

src/miman_s_control.s: src/miman_s_control.cpp.s

.PHONY : src/miman_s_control.s

# target to generate assembly for a file
src/miman_s_control.cpp.s:
	$(MAKE) -f CMakeFiles/MIMAN.dir/build.make CMakeFiles/MIMAN.dir/src/miman_s_control.cpp.s
.PHONY : src/miman_s_control.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... MIMAN"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/miman_autopilot.o"
	@echo "... src/miman_autopilot.i"
	@echo "... src/miman_autopilot.s"
	@echo "... src/miman_coms.o"
	@echo "... src/miman_coms.i"
	@echo "... src/miman_coms.s"
	@echo "... src/miman_config.o"
	@echo "... src/miman_config.i"
	@echo "... src/miman_config.s"
	@echo "... src/miman_csp.o"
	@echo "... src/miman_csp.i"
	@echo "... src/miman_csp.s"
	@echo "... src/miman_ftpfcd.o"
	@echo "... src/miman_ftpfcd.i"
	@echo "... src/miman_ftpfcd.s"
	@echo "... src/miman_ftprdp.o"
	@echo "... src/miman_ftprdp.i"
	@echo "... src/miman_ftprdp.s"
	@echo "... src/miman_imgui.o"
	@echo "... src/miman_imgui.i"
	@echo "... src/miman_imgui.s"
	@echo "... src/miman_model.o"
	@echo "... src/miman_model.i"
	@echo "... src/miman_model.s"
	@echo "... src/miman_orbital.o"
	@echo "... src/miman_orbital.i"
	@echo "... src/miman_orbital.s"
	@echo "... src/miman_radial.o"
	@echo "... src/miman_radial.i"
	@echo "... src/miman_radial.s"
	@echo "... src/miman_s_control.o"
	@echo "... src/miman_s_control.i"
	@echo "... src/miman_s_control.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

